stages:
  - build

.build:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE:latest" || true
    - docker build -t "$CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG" --cache-from "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG"

build-master:
  extends: .build
  stage: build
  variables:
    DOCKER_IMAGE_TAG: latest
  only:
    - master

build-tags:
  extends: .build
  stage: build
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME
  only:
    - tags
